//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftUniDBContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SoftUniContext : DbContext
    {
        public SoftUniContext()
            : base("name=SoftUniContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Town> Towns { get; set; }
    
        public virtual ObjectResult<usp_AllProjectsByEmployee_Result> usp_AllProjectsByEmployee(string employeeFirstName, string employeeLastName)
        {
            var employeeFirstNameParameter = employeeFirstName != null ?
                new ObjectParameter("employeeFirstName", employeeFirstName) :
                new ObjectParameter("employeeFirstName", typeof(string));
    
            var employeeLastNameParameter = employeeLastName != null ?
                new ObjectParameter("employeeLastName", employeeLastName) :
                new ObjectParameter("employeeLastName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_AllProjectsByEmployee_Result>("usp_AllProjectsByEmployee", employeeFirstNameParameter, employeeLastNameParameter);
        }
    }
}
